name: cms-portfolio-laravel
services:
- name: web
  source_dir: /
  github:
    repo: cesarolvrdz/cms-portfolio-laravel
    branch: main
    deploy_on_push: true
  run_command: |
    php artisan config:cache
    php artisan route:cache
    php artisan view:cache
    php artisan migrate --force
    php artisan db:seed --force
    php-fpm
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: APP_NAME
    value: "CMS Portfolio"
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "false"
  - key: APP_URL
    value: ${APP_URL}
  - key: APP_KEY
    value: ${APP_KEY}
  - key: DB_CONNECTION
    value: pgsql
  - key: DB_HOST
    value: ${db.HOSTNAME}
  - key: DB_PORT
    value: ${db.PORT}
  - key: DB_DATABASE
    value: ${db.DATABASE}
  - key: DB_USERNAME
    value: ${db.USERNAME}
  - key: DB_PASSWORD
    value: ${db.PASSWORD}
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: SESSION_DRIVER
    value: file
  - key: CACHE_DRIVER
    value: file
  - key: QUEUE_CONNECTION
    value: sync
  - key: MAIL_MAILER
    value: smtp
  - key: SUPABASE_URL
    value: ${SUPABASE_URL}
  - key: SUPABASE_SERVICE_KEY
    value: ${SUPABASE_SERVICE_KEY}
  - key: SUPABASE_BUCKET_CV
    value: ${SUPABASE_BUCKET_CV}
  - key: SUPABASE_BUCKET_CERTIFICATES
    value: ${SUPABASE_BUCKET_CERTIFICATES}
  - key: SUPABASE_BUCKET_PORTFOLIO
    value: ${SUPABASE_BUCKET_PORTFOLIO}

databases:
- name: db
  engine: PG
  num_nodes: 1
  size: db-s-dev-database
  version: "15"
